---
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended

plugins:
  - "@typescript-eslint"
  - react
  - react-hooks

parser: "@typescript-eslint/parser"

globals:
  page: true
  browser: true
  context: true
  jestPuppeteer: true
  BASE_URL: true

rules:
  # Code quality rules
  "@typescript-eslint/no-empty-function": ["error", { "allow": ["arrowFunctions"] }]
  no-unused-vars: off
  "@typescript-eslint/no-unused-vars": ["error", { "argsIgnorePattern": "^_", "destructuredArrayIgnorePattern": "^_" }]
  no-use-before-define: off
  "@typescript-eslint/no-use-before-define": ["error", { "functions": false }]
  "@typescript-eslint/no-var-requires": off # Remove this override once all files use ES6 style imports.
  prefer-const: ["error", {"destructuring": "all"}]
  react/no-array-index-key: error
  react/prop-types: off # Remove this override once all props have been typed using PropTypes or TypeScript.
 
  # Allow typescript line-disabling _if_ we use a comment to explain why
  "@typescript-eslint/ban-ts-comment": ["error", {'ts-expect-error': 'allow-with-description'}]

  # Code style rules
  arrow-parens: ["error", "always"]
  no-unneeded-ternary: ["error", { "defaultAssignment": true }]
  operator-linebreak: ["error", "after", { "overrides": { "?": "ignore", ":": "ignore" } }]
  quote-props: ["error", "as-needed"]

parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    modules: true

env:
  es6: true
  browser: true
  node: true
  jest: true

settings:
  react:
    version: detect
