import React from 'react';
import Radium from 'radium';
// import _ from 'lodash';
import Flex from './framework/flex';
// import { connect } from 'react-redux';
// import { FOO } from '../actions';
import Logos from "./logos";

// @connect(state => {
//   return state.FOO;
// })
@Radium
class Footer extends React.Component {
  constructor(props) {
    super(props);
    this.state = {

    };
  }
  static propTypes = {
    /* react */
    // dispatch: React.PropTypes.func,
    params: React.PropTypes.object,
    routes: React.PropTypes.array,
    /* component api */
    style: React.PropTypes.object,
    // foo: React.PropTypes.string
  }
  static defaultProps = {
    // foo: "bar"
  }
  getStyles() {
    return {
      base: {

      }
    };
  }
  render() {
    const styles = this.getStyles();
    return (
      <div style={[
        styles.base,
        this.props.style
      ]}>
        {`Built by `}
        <a href="https://neherlab.wordpress.com/">
          Richard Neher
        </a>
          {` and `}
        <a href="http://bedford.io">
          Trevor Bedford
        </a>
        {`. `}
        {`This work is made possible by the `}
        <a href="http://gisaid.org" target="_blank">
          {`GISAID Initiative`}
        </a>
        {` and the open sharing of genetic data by influenza research groups from all over the world. `}
        <a href="/acknowledgements/">
          {` We gratefully acknowledge their contributions.`}
        </a>
        {` Recent HI titer data was generated by John McCauley, Rod Daniels and colleagues at the `}
        <a href="http://www.crick.ac.uk/research/worldwide-influenza-centre">
          {`Worldwide Influenza Centre at the Francis Crick Institute`}
        </a>
        {`. Give us a shout at`}
        <a href="https://twitter.com/richardneher" target="_blank">
          @richardneher
        </a>
        {` or `}
        <a href="https://twitter.com/trvrb" target="_blank">
          {` @trvrb `}
        </a>
        {` with questions or comments. All `}
        <a href="http://github.com/blab/nextflu" target="_blank">
          {`source code`}
        </a>
        {` is freely available under the terms of the `}
        <a href="http://github.com/blab/nextflu/blob/master/LICENSE.txt" target="_blank">
          {`GNU Affero General Public License`}
        </a>
        {`. A `}
        <a href="/methods/">
          {`detailed description of methods`}
        </a>
        {` is also available. Data updated `}
        <span id="updated"></span>
        {` and processed with commit`}
        <span id="commit"></span>
        {`. `}
        <p>
          {`Please cite: `}
          <a href="http://dx.doi.org/10.1093/bioinformatics/btv381">
            {`Neher RA, Bedford T. 2015. nextflu: real-time tracking of seasonal influenza virus evolution in humans. Bioinformatics 10.1093/bioinformatics/btv381`}
          </a>
          {`.`}
        </p>

        {`&copy; 2015-2016 Trevor Bedford and Richard Neher`}
          <Logos/>
      </div>
    );
  }
}

export default Footer;
