name: "Make PR for a repository which depends on Auspice"
on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      directory:
        required: false
        type: string
        default: .
jobs:
  make-pr-on-downstream-repo:
    # I don't see this being used for tags, so ensure it's only run on branches
    # to make subsequent logic and wording easier.
    if: github.ref_type == 'branch'

    runs-on: ubuntu-latest

    env:
      DESTINATION_REPO_DIR: repo

    steps:
      # Outputs:
      # - pr-number: The PR number from the branch name (exits if no PR exists).
      # - auspice-sha: The GitHub-managed merge ref. Used for npm install.
      #
      # Note that $GITHUB_SHA shouldn't be used here because it refers to the
      # branch HEAD which is not merged with the PR target branch. If the
      # workflow trigger event was `pull_request` then it would refer to the
      # merge ref¹, but we use `workflow_dispatch` to reduce the number of PRs.
      #
      # ¹ https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
      - name: Detect PR from branch
        id: detect-pr
        run: |
          PR_NUMBER=$(gh pr view $GITHUB_REF_NAME --repo nextstrain/auspice --json 'number' --jq '.number') || true
          if [[ -z $PR_NUMBER ]]; then
            echo "ERROR: This branch is not associated with a PR in Auspice." >&2
            exit 1
          fi
          MERGE_SHA=$(gh pr view $GITHUB_REF_NAME --repo nextstrain/auspice --json 'potentialMergeCommit' --jq '.potentialMergeCommit.oid')
          echo "pr-number=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "auspice-sha=$MERGE_SHA" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Checkout downstream repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          path: ${{ env.DESTINATION_REPO_DIR }}
          token: ${{ secrets.GH_TOKEN_NEXTSTRAIN_BOT_REPO }}

      - name: Install Auspice from PRs HEAD commit
        shell: bash
        working-directory: ${{ env.DESTINATION_REPO_DIR }}/${{ inputs.directory }}
        run: |
          npm ci
          npm install nextstrain/auspice#${{ steps.detect-pr.outputs.auspice-sha }}
          git add package.json package-lock.json

      - name: Create Pull Request
        working-directory: ${{ env.DESTINATION_REPO_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_NEXTSTRAIN_BOT_REPO }}
          title: '[bot] [DO NOT MERGE] Test Auspice PR ${{ steps.detect-pr.outputs.pr-number }}'
          body: |
            This PR has been created to test this project running Auspice with changes from https://github.com/nextstrain/auspice/pull/${{ steps.detect-pr.outputs.pr-number }}.

            Note that Auspice has been installed with changes from both the PR's source and target branches.
            This will surface any issues that can arise from merging the PR in Auspice. To address these issues locally, update the source branch (e.g. with a git rebase).

            This message and corresponding commits were automatically created by a GitHub Action from [nextstrain/auspice](https://github.com/nextstrain/auspice).
          body_file: pr_body.txt
        run: |
          git config user.name "nextstrain-bot"
          git config user.email "nextstrain-bot@users.noreply.github.com"

          git switch -c "nextstrain-bot/test-auspice-pr/${{ steps.detect-pr.outputs.pr-number }}"
          git commit --message="[testing only] Upgrade Auspice to ${{ github.sha }}"
          git push -u origin HEAD

          echo "$body" > "$body_file"
          pr_url="$(gh pr create --title "$title" --body-file "$body_file" --draft)"
          echo "Pull request created for ${{ inputs.repository }}: $pr_url" >> "$GITHUB_STEP_SUMMARY"
